// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkingWithCSVFile;

namespace WorkingWithCSVFile.Migrations
{
    [DbContext(typeof(OffersDbContext))]
    [Migration("20210418184748_InitialDatabaseMigration")]
    partial class InitialDatabaseMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WorkingWithCSVFile.Offer", b =>
                {
                    b.Property<int>("OfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("offerId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CancelledContractsForMonth")
                        .HasColumnType("int")
                        .HasColumnName("CancelledContractsForMonth");

                    b.Property<double>("MonthlyFee")
                        .HasColumnType("float")
                        .HasColumnName("monthlyFee");

                    b.Property<int>("NewContractsForMonth")
                        .HasColumnType("int")
                        .HasColumnName("newContractsForMonth");

                    b.Property<int>("SameContractsForMonth")
                        .HasColumnType("int")
                        .HasColumnName("sameContractsForMonth");

                    b.HasKey("OfferId");

                    b.ToTable("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
